### ISSUE TITLE
couple of panics in the library

### ISSUE THREAD

**Issue by jessfraz** [oxidecomputer/steno#12]
here is an example: https://github.com/oxidecomputer/steno/blob/main/src/sec.rs#L265

Can I make a PR to change these to errors? or maybe log a warning? just don't want my whole server to panic when it occurs.

I am getting one of them quite a few times, unsure if this is valuable data

<img width="1259" alt="Screen Shot 2021-09-12 at 8 42 02 AM" src="https://user-images.githubusercontent.com/1445228/132993909-4368c125-8196-47a0-a07a-7a5315d6a6d3.png">

**Comment by davepacheco** [comment]
Sorry for the trouble.  There's a bunch of discussion on the various cases we panic (including the one you mentioned) in #16.  From my understanding, you'd hit these today only after you hit an internal bug in Steno from which we cannot recover.  I don't see that in your screenshot -- I only see the follow-on panics.  It'd be good to get that first problem understood.

Given that we've hit an unrecoverable error, we panic any time you try to use the SecClient again.  We do that because Nexus is probably going to want to do that.  We could in principle return an error instead, but what is your program trying to do when it's calling shutdown?  What would you do with an error at that point that means that all future calls to the SecClient will produce that error, too?

**Comment by davepacheco** [comment]
I don't think there's enough information here to root-cause the initial problem.  #32 covers avoiding panicking on consumer misuse.  I'm not sure if trying to use the SEC object after shutting it down would count.
